import Sidebar from '@/components/sidebar/Sidebar'
import './globals.css'
import type { Metadata } from 'next'
import { Cairo } from 'next/font/google'
import Navbar from '@/components/navbar/Navbar'

const font = Cairo({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Dashboard - Weframetech',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${font.className} bg-dark01 flex`}>
        <Sidebar />
        <main className='w-full h-full'>
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  )
}
